### ISSUE TITLE
Sources should retain compatibility with JDK version specified in the README

### ISSUE THREAD

**Issue by Argent77** [NearInfinityBrowser/NearInfinity#115]
Readme specifies JDK 8 as minimum requirement.

The following code is currently causing a compile error:
```
[javac] src/org/infinity/gui/SortableTable.java:305: error: cannot find symbol
[javac]         res = Arrays.compare(arr1, arr2, SORTER);
[javac]                     ^
[javac]   symbol:   method compare(String[],String[],Comparator<String>)
[javac]   location: class Arrays
```
`Arrays.compare` was introduced by JDK 9.

Possible solutions:
1. Re-implement `Arrays.compare` with JDK 8 compliant code.
2. Adjust minimum requirements in the README.

Unless future implementations make heavy use of JDK 9+ features, I'd suggest to apply solution 1.

**Comment by Mingun** [comment]
Now I do not plan use Java 9 features, so I also prefer solution 1
