### ISSUE TITLE
Add ability to quick find objects with the some property value

### ISSUE THREAD

**Issue by Mingun** [NearInfinityBrowser/NearInfinity#120]
Item in the context menu of the property must display the **Extended search** dialog, select right type of objects and populate the first custom filter with property name and type:
![FindByProperty](https://user-images.githubusercontent.com/450131/68524258-75c80d80-02e6-11ea-9f8e-910cbd50ef70.png)

**Comment by Argent77** [comment]
A similar functionality is already implemented as `Find...` > `selected attribute`.
