### ISSUE TITLE
iwd2 CHU files are cut off

### ISSUE THREAD

**Issue by lynxlynxlynx** [NearInfinityBrowser/NearInfinity#124]
IWD2 had a 800x600 minimum resolution and the data in the chus cannot be trusted. If you open start.chu, it gets cut off, since it reports a 640x480 size, while it's clearly bigger. This is visible also in other windows from the same chu. It's probably also the reason that control outline display is misplaced.

**Comment by Mingun** [comment]
How this situation is handled in GemRB?

**Comment by lynxlynxlynx** [comment]
We manually specify the minimum size (800x600).

**Comment by Argent77** [comment]
Fixed in 8512e58f2465762cbfe79ff81eafccac0600eb71.

**Comment by lynxlynxlynx** [comment]
Thanks!
