### ISSUE TITLE
FR: better use of space in the extended header view

### ISSUE THREAD

**Issue by lynxlynxlynx** [NearInfinityBrowser/NearInfinity#126]
It's annoying to have to scroll through the effect list, especially since it's not just vertical:
![image](https://user-images.githubusercontent.com/121515/71371254-d8344f00-25b0-11ea-8bce-b1f330526e08.png)

**Comment by Argent77** [comment]
Commit cec6a6d1993390cf27a3c5506888fe08f5e8854f should improve situation somewhat.
