### ISSUE TITLE
special characters in french (or other language)

### ISSUE THREAD

**Issue by Jeanpierregi** [NearInfinityBrowser/NearInfinity#127]
Hi,

in the texts, where strring are used, text is displayed "correctly" as in game.

But when you copy/paste this in a tp2 file, you have to use some kind of strange characters, such as :
é = Ã©
è = Ã¨
à = Ã 
ê = Ãª

could you provide some option in NI to be able to display the text "as with those" to help copy/paste text?

**Comment by Argent77** [comment]
That has nothing to do with Near Infinity. It looks like your text editor doesn't recognize the character encoding of the copied text. Many UTF-8-encoded characters consist of multiple bytes, which results in the random characters you have listed above if the text is interpreted as ANSI.

EE games use UTF-8 encoding by default. Classic games use ANSI encoding (code page depends on the localization).

Many text editors allow you to specify the character encoding or can autodetect the encoding. For Windows I'd recommend [Notepad++](https://notepad-plus-plus.org/).
