### ISSUE TITLE
Displaying TobEx effect stacking ID

### ISSUE THREAD

**Issue by burner1024** [NearInfinityBrowser/NearInfinity#131]
> TobEx allows modmakers to configure when effects can stack. This is achieved by implementing bit 25 (Limit Effect Stacking) of the EFF V2.0 Header offset 0x0040 (Save Type), ITM V1.0 Feature Block offset 0x0024 (Save Type), and SPL V1.0 Feature Block offset 0x0024 (Save Type).
> ...
> Stacking IDs are unique to the opcode being applied. To maintain uniqueness of stacking IDs between different mods, one recommendation is to use the higher word of Special as the modder's Infinity Engine Community Prefix, then use the lower word as an identifying ID. For example, 0x41360001 ('A6' 0x0001).

If possible, it would be nice to see  the ID displayed in this ascii+num form ('A6' 0x0001).

> TobEx also implements bit 26 (Internal: Suspend Effect Application) of the EFF V2.0 Header offset 0x0040 (Save Type), ITM V1.0 Feature Block offset 0x0024 (Save Type), and SPL V1.0 Feature Block offset 0x0024 (Save Type) to prevent effects with limited stacking from being applied.

And this one should probably be marked as reserved by Tobex? (I don't fully understand why it's needed, but what I gather from the description is that it shouldn't be set manually).

Ref [IESDP](https://github.com/Gibberlings3/iesdp/pull/92).

**Comment by Argent77** [comment]
Adding fields for ID and prefix is certainly possible. However, it would have to be added statically regardless of flags bit 25 set or not.

The internal flag "Suspend Effect Application" is not really useful though, imo. It's just an implementation detail for TobEx and probably only visible for creature effects in saved games (if at all).

**Comment by burner1024** [comment]
> Adding fields for ID and prefix is certainly possible. However, it would have to be added statically regardless of flags bit 25 set or not.

Why yes, of course, I didn't mean it otherwise. My emphasis was on _how_ to display it.

> The internal flag "Suspend Effect Application" is not really useful though, imo. It's just an implementation detail for TobEx and probably only visible for creature effects in saved games (if at all).

Well, it's mostly for completeness, and so that any authors of other any engine mods/hacks are aware that it's reserved by TobEx. I think it'd be better to have it, but I don't insist, so whatever you decide.

**Comment by Argent77** [comment]
> 
> > Adding fields for ID and prefix is certainly possible. However, it would have to be added statically regardless of flags bit 25 set or not.
> 
> Why yes, of course, I didn't mean it otherwise. My emphasis was on _how_ to display it.

TobEx field descriptions are actually straightforward in that regard: it would be a numeric field for the identifier and a text field for the modder prefix (both 2 bytes in size).

> > The internal flag "Suspend Effect Application" is not really useful though, imo. It's just an implementation detail for TobEx and probably only visible for creature effects in saved games (if at all).
> 
> Well, it's mostly for completeness, and so that any authors of other any engine mods/hacks are aware that it's reserved by TobEx.

I wouldn't worry too much about it. Chances for a new TobEx-like engine hack are rather slim nowadays.

**Comment by burner1024** [comment]
well, there's EEEx, I understand it's in more or less active development

**Comment by Argent77** [comment]
Added: https://github.com/Argent77/NearInfinity/commit/b7951b6bfb8cf4cd9977ed06f78b3258954b99df

**Comment by burner1024** [comment]
Thank you!
One minor nitpick, though: I think the endianness is reversed: 0x4136 is displayed as 6A.
![Captura de pantalla de 2020-06-19 19-29-32](https://user-images.githubusercontent.com/1279852/85132739-91739900-b263-11ea-97ab-bdf7949b705a.png)
(Well, it doesn't matter much, just making sure you know.)

**Comment by Argent77** [comment]
> 
> One minor nitpick, though: I think the endianness is reversed: 0x4136 is displayed as 6A.

There is no endianness involved for (single-byte) characters in text fields. I'd say the string interpretation of the example in the TobEx readme (0x4136 -> 'A6') is incorrect. Lower byte (0x36 -> '6') translates to offset 0. Upper byte (0x41 -> 'A') translates to offset 1. So the resulting string is '6A'.

**Comment by burner1024** [comment]
Yes, I understand. It's your decision, I just hope it won't lead to confusion. It's probably used very rarely anyway.
