### ISSUE TITLE
Filtering opcodes

### ISSUE THREAD

**Issue by burner1024** [NearInfinityBrowser/NearInfinity#132]
Currently, when you search for an opcode in effect window, it just skips to the first match. I was wondering, maybe a better UX would be to filter them for the entered words as they are entered?
![Captura de pantalla de 2020-07-14 16-42-19](https://user-images.githubusercontent.com/1279852/87411090-675a9000-c5f1-11ea-94f3-b0885a30152e.png)

**Comment by Argent77** [comment]
Although I prefer the current behavior of the list boxes, a filter feature would be useful in certain situations. I'll see what I can do.

**Comment by Mingun** [comment]
I think, Global setting + local button *Filter/Select* can be implemented, like in VS Code in Workplace/Project tree etc.

**Comment by Argent77** [comment]
Added: https://github.com/Argent77/NearInfinity/commit/b9e2d8028c213c62200aeb9d02011d2e67d13dec
