### ISSUE TITLE
Feature request: implement existing TODO :)

### ISSUE THREAD

**Issue by lynxlynxlynx** [NearInfinityBrowser/NearInfinity#135]
This one:
https://github.com/NearInfinityBrowser/NearInfinity/blob/08e2f79e6a76367540ebc20a8b086e127b0f3698/src/org/infinity/resource/Profile.java#L1681

I'm trying to make NI more useful for our demo and now I have to add fake files for it to chose a game type.

**Comment by Argent77** [comment]
I totally forgot about that one. ;)

You can already enforce a specific game type via command line parameter, e.g.
```
java -jar NearInfinity.jar -t bg2tob
```

Call `java -jar NearInfinity.jar -help` for a full list of available options.

**Comment by lynxlynxlynx** [comment]
Oh, that's handy. I have to switch a lot, so an interactive version would still be preferred though.

**Comment by Argent77** [comment]
Added: https://github.com/Argent77/NearInfinity/commit/5bbbc48558aee189a2a46ae643c82a58cf58c46c

**Comment by lynxlynxlynx** [comment]
Thanks!
