### ISSUE TITLE
De-sillify game ID

### ISSUE THREAD

**Issue by FredrikLindgren** [NearInfinityBrowser/NearInfinity#14]
Game ID should reflect actual engine differences. Get rid of the pointless ID_TUTU and farm out cosmetic differences like GameName to some secondary code (where support for Tutu and BGT is added).

**Comment by Argent77** [comment]
Replaced game id system with a more flexible game profile system. [Commit](https://github.com/Argent77/NearInfinity/commit/d338d09ce0d99a2c8a80b4c2bfb97ea1381caa45)
