### ISSUE TITLE
BIF archives in data subdirectory are not found by NI

### ISSUE THREAD

**Issue by nsajko** [NearInfinityBrowser/NearInfinity#140]
While using NI with original PST from GOG.com I stumbled upon a pretty serious bug, but with a workaround.

Some BIF files are in the root PST dir, but that is not the only directory with BIF file: at least the data subdirectory also contains some BIF files.

When I first ran NI on my PST installation, it listed certain files (archived in some BIF files) in its GUI, but then could not open them.

However (this is the workaround), if I copy some of those BIFs to the root directory, NI can find their files just fine.

This is on Linux, with NI 6d0d1a587866bfba790820f15a807e81740d031c.

**Comment by Argent77** [comment]
This is most likely related to issue #137.

As an interim solution I have added the command line parameter `-i` to release v2.2-20210501 that should work around this issue until the more fundamental problem has been solved. Call NI from the command line with: `java -jar NearInfinity.jar -i`

Alternatively, you could use an older NI release instead if you don't need the latest features.

**Comment by burner1024** [comment]
> Alternatively, you could use an older NI release instead if you don't need the latest features.

Sorry, which one would that be?

**Comment by Argent77** [comment]
This issue should be solved by [v2.2-20211218](https://github.com/Argent77/NearInfinity/releases/tag/v2.2-20211218).
