### ISSUE TITLE
command line for running checks

### ISSUE THREAD

**Issue by burner1024** [NearInfinityBrowser/NearInfinity#141]
Hi.
Would it be too much trouble to add a command line mode and expose NI resource integrity checks there?
I'm wondering about integrating NI into [Golem](https://golem.bgforge.net/).

**Comment by Argent77** [comment]
Unfortunately that's not possible without a major rewrite. Most of NI's functionality is closely tied to the UI representation. That also includes the integrity checks.

**Comment by burner1024** [comment]
I see, well, gonna have to go the long way, then.
