### ISSUE TITLE
CAB Background customize color also colors the shadow

### ISSUE THREAD

**Issue by yjeroen** [NearInfinityBrowser/NearInfinity#145]
![image](https://user-images.githubusercontent.com/1303988/150588658-ee545964-c1d3-4618-b16c-cc3fad82d8e1.png)

vs Background System Color

![image](https://user-images.githubusercontent.com/1303988/150588692-7ba7fb6d-6c47-43ad-9634-d6b00caed746.png)

**Comment by Argent77** [comment]
That's intended. Creature shadows are semitransparent, so the background will shine through partially.
