### ISSUE TITLE
Can't access SoD saves

### ISSUE THREAD

**Issue by CamDawg** [NearInfinityBrowser/NearInfinity#147]
On BGEE games with Siege of Dragonspear installed, the save games in the sodsave folder are not listed in the file tree. 

This is on a clean install from the Beamdog launcher--not even DLC Merger is installed.

**Comment by Argent77** [comment]
Thanks. It looks like a bug in the 2DA table parser. Will be fixed.

**Comment by CamDawg** [comment]
Cheers, and thanks as always!

**Comment by Argent77** [comment]
[Fixed](https://github.com/Argent77/NearInfinity/commit/d9f6937f80a3c049297703dacdb38e57c0a8289b).
