### ISSUE TITLE
Option to disable prompt when switching games

### ISSUE THREAD

**Issue by CamDawg** [NearInfinityBrowser/NearInfinity#149]
Always loved the bookmarked games feature, strongly dislike the 'open bookmarked game' prompt that was added in the most recent version. Is there an option to disable it and, if not, can one be added?

**Comment by Argent77** [comment]
Sure, I can add this option.

**Comment by Argent77** [comment]
Added: e0e5cbbe50495afdf1babfb5141237a107900d00

It'll probably take some time until the next release. Can you build NI yourself, or should I build it and attach it to this issue?

**Comment by lynxlynxlynx** [comment]
Same here. What was the rationale in the first place?

**Comment by Argent77** [comment]
With the addition of keyboard shortcuts there is a risk to accidentally switch the game by pressing the wrong key (in the worst case without the user even noticing it). A confirmation prompt should prevent it.

**Comment by lynxlynxlynx** [comment]
I'm not sure I read the code well, so I'll just say it here: the popup should be opt-in, not opt-out, since most users won't use keyboard shortcuts for this.

**Comment by Argent77** [comment]
But that would basically defeat the purpose of the safety mechanism, since it's not obvious that there is an option for it in the first place. (Unless you read the changelog or wiki, but who does?)

**Comment by lynxlynxlynx** [comment]
Ok, how about making the popup have a setting checkbox, so you can just tick "don't bother me again" when you get it? It would toggle the main setting, so it'd still be configurable, but then there are no discoverability issues for either side.

**Comment by Argent77** [comment]
NI uses premade confirmation dialogs from the Swing UI library. I can probably add something like that if there's a way to customize these dialogs. Implementing a custom dialog class just for this instance would be overkill.

**Comment by Argent77** [comment]
> Ok, how about making the popup have a setting checkbox, so you can just tick "don't bother me again" when you get it? It would toggle the main setting, so it'd still be configurable, but then there are no discoverability issues for either side.

Added (https://github.com/Argent77/NearInfinity/commit/71b48eb1899257b37ee4088b8ed0a432cf736e6a and https://github.com/Argent77/NearInfinity/commit/8c637ca4e7754476ee85e25b789da7f39790f694).
