### ISSUE TITLE
Compilation broken on v2.4-20230625

### ISSUE THREAD

**Issue by Insomniator** [NearInfinityBrowser/NearInfinity#160]
JDK 17.0.7 x64, Ant 1.10.13

**c:\Temp\NearInfinity-2.4-20230625**>ant
ANT_OPTS is set to  -Djava.security.manager=allow
Buildfile: c:\Temp\NearInfinity-**2.4-20230625**\build.xml

clean:

compile:
    [mkdir] Created dir: c:\Temp\NearInfinity-2.4-20230625\build\src
    [javac] Compiling 1107 source files to c:\Temp\NearInfinity-2.4-20230625\build\src
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] c:\Temp\NearInfinity-2.4-20230625\src\org\infinity\gui\ PreferencesDialog.java:691: **error: incompatible types: inference variable T has incompatible equality constraints DefaultMutableTreeNode,TreeNode
    [javac]     final ArrayList<DefaultMutableTreeNode> list = Collections.list(node.children());
    [javac]                                                                    ^
    [javac]   where T is a type-variable:
    [javac]     T extends Object declared in method <T>list(Enumeration<T>)**
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 error
    [javac] 1 warning

**BUILD FAILED**
c:\Temp\NearInfinity-2.4-20230625\build.xml:34: Compile failed; see the compiler error output for details.

**c:\Temp\NearInfinity-2.3-20230610**>ant
ANT_OPTS is set to  -Djava.security.manager=allow
Buildfile: c:\Temp\NearInfinity-**2.3-20230610**\build.xml

clean:

compile:
    [mkdir] Created dir: c:\Temp\NearInfinity-2.3-20230610\build\src
    [javac] Compiling 1084 source files to c:\Temp\NearInfinity-2.3-20230610\build\src
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 8
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 1 warning
     [copy] Copying 199 files to c:\Temp\NearInfinity-2.3-20230610\build\src
      [jar] Building jar: c:\Temp\NearInfinity-2.3-20230610\NearInfinity.jar

**BUILD SUCCESSFUL**
Total time: 11 seconds

**Comment by Argent77** [comment]
Fixed in Argent77/NearInfinity@75d3dc8bbcd8a586a1835dfc5041ee1e6bbaed22

I strongly recommend to build Near Infinity with Java 8, however. The code contains many compatibility issues which cannot be resolved without dropping Java 8 support.

**Comment by Insomniator** [comment]
> I strongly recommend to build Near Infinity with Java 8, however. The code contains many compatibility issues which cannot be resolved without dropping Java 8 support.
Problem is documentation, it says "Required tools: Oracle's Java SE Development Kit 8 **or later**, or OpenJDK 8 **or later**", may be need to more clarify what JDK expected...

**Comment by Argent77** [comment]
Yes, it is possible to build NI with more recent versions of Java. However, they are not fully tested.

Java 9 introduced many changes to the API which, in some cases, also changed the original Java 8 behavior. A good example is the L&F handling on macOS which produces an error message on later Java versions and cannot be fixed without dropping Java 8 support.

I haven't encountered any critical issues yet, however. So this is just my personal recommendation and not a hard requirement.
