### ISSUE TITLE
Unused file search issue?

### ISSUE THREAD

**Issue by Salk73** [NearInfinityBrowser/NearInfinity#167]
Hello!

I made a search about unused .wav files and among the many reported files, I noticed several from the SSWORDxx group. Near Infinity (v.2.4-20230625) indicated many files from that group to be unused while instead they are (found in baldur.bcs and baldur25.bcs).

I was using NI with Baldur's Gate Trilogy.

**Comment by Argent77** [comment]
I'll look into it.

**Comment by Argent77** [comment]
Issue should have been fixed in 99fe6f7. Sorry for the delay.

It can already been tested in the [nightly release](https://github.com/Argent77/NearInfinity/releases/tag/nightly).
