### ISSUE TITLE
Multi-language interface requirements

### ISSUE THREAD

**Issue by MephistoSatanDevil** [NearInfinityBrowser/NearInfinity#179]
Is it possible to make NearInfinity window available in multiple languages?

**Comment by Argent77** [comment]
You've asked the same question there some time ago: https://github.com/NearInfinityBrowser/NearInfinity/discussions/173

Short answer: No, it is practically not possible to add multi-language support to Near Infinity.

**Comment by MephistoSatanDevil** [comment]
> You've asked the same question there some time ago: #173
> 
> Short answer: No, it is practically not possible to add multi-language support to Near Infinity.

ok, thank you for answer.
