### ISSUE TITLE
Possible memory leak when using "Find references" on PVRZ

### ISSUE THREAD

**Issue by Incrementis** [NearInfinityBrowser/NearInfinity#182]
As the title describes, that's what I experienced. Following are some hardware/Software specifications and reproducibility steps.

- **Operating System:** Microsoft Windows 11 Home

- **Memory:** 80,0 GB (RAM)
- **JAVA:**
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)
- **Near Infinity:**
![grafik](https://github.com/NearInfinityBrowser/NearInfinity/assets/17119474/204e0570-b8fa-4489-86c6-e38a3c8f1a79)
- **Game:** Baldur's Gate: Siege of Dragonspear

**Steps for reproducability:**
1. Start NearInfinity.jar (See image below for memory usage is about 1.3GB)
![2024-06-24 16_45_55-NVIDIA GeForce Overlay](https://github.com/NearInfinityBrowser/NearInfinity/assets/17119474/ac839af2-b6f1-4084-a603-39fcbb25875a)

3. Navigate to PVRZ folder
4. Right click **A000200.PVRZ** and select "_Find references_"
5. Keep all checkboxes selected and press "_Search_" button
6. The most time-consuming and memory-intensive operation occurs between processing TISs **18900/19181** and **19000/19181** (see image below)
![2024-06-24 16_47_49-Near Infinity - Baldur's Gate_ Siege of Dragonspear](https://github.com/NearInfinityBrowser/NearInfinity/assets/17119474/f92881fa-4f48-46f9-b795-9dd1e2ad8295)

8. Refreshing with **F5** or “_Game->RefreshTree_” does not release memory usage (Perhaps some sort of garbage collector could help after the search results, if that is even implementable?)
9. Closing application and restarting helps.

**Comment by Argent77** [comment]
Memory in Java applications is generally managed by the Java VM itself. It is possible to hint that objects are not used anymore, but it's the JVM that decides if or when memory should be released. Even triggering the garbage collector directly doesn't always result in released memory.

The system information on the main panel displays the memory available to the Java application. I don't think there is a reason to be concerned as memory consumption doesn't reach or exceed that value.

Did you notice any slowdowns after performing these memory-intensive operations?

**Comment by Incrementis** [comment]
"_Did you notice any slowdowns after performing these memory-intensive operations?_"

There are no noticeable slowdowns. NI works smoothly as if it didn't need that amount of memory.
It would be interesting to see how things would behave with 8 or 16 GB of RAM, because if I'm not mistaken, many laptops come with that much RAM installed by default.

**Comment by Argent77** [comment]
NI wouldn't consume as much memory if the total memory was only 8 or 16 GB, or more specifically, allocated objects would be released more frequently if available RAM was smaller. The same operation on my desktop system with 64 GB RAM consumed only about 5 GB memory.

Garbage collection is a rather complicated process and operates mostly outside of application control. This article provides a good overview: https://newrelic.com/blog/best-practices/java-garbage-collection
