### ISSUE TITLE
NearInfinity 1.3.0 issues on Ubuntu 22.04 - baldur.ini, finding *.bif related

### ISSUE THREAD

**Issue by russellmatt66** [NearInfinityBrowser/NearInfinity#186]
Hi, sorry if the solution to this is somewhere that I haven't found yet, but I'm trying to use NearInfinity on Ubuntu 22.04, and running into issues related to the non-existence of `baldur.ini` - it's `baldur.lua`, and elsewhere than NI expects - and the subsequent finding of `.bif` files. 

I've made a post on the Beamdog forums that compiles all this information, as well as the exact steps I'm taking that produce the errors, and the errors themselves. 

Here it is: https://forums.beamdog.com/discussion/88828/nearinfinity-1-3-0-ci-issue-with-loading-bif-files-ubuntu-22-04#latest

I would love to understand what the fundamental problem is here, and how to solve it. I know where `baldur.lua` is, but I don't know where I need to go to tell NearInfinity that, because all I can point it to is `chitin.key` for my IWD:EE installation..

**Comment by Argent77** [comment]
From your Beamdog forums post:
```bash
mycomputer:path/to/cwd$ java -jar NearInfinity-1.3.0-ci.jar
```
That version of Near Infinity is over 10 years old and hopelessly outdated by now.

You can grab a more up to date version from here: https://github.com/Argent77/NearInfinity/releases

Alternatively install the FlatHub version: https://flathub.org/apps/io.github.nearinfinitybrowser.nearinfinity

It should solve most if not all your problems.
