### ISSUE TITLE
Area files should always show area script

### ISSUE THREAD

**Issue by lynxlynxlynx** [NearInfinityBrowser/NearInfinity#188]
IWD2 ar6300 displays "Area script: None" in the GUI, since it has the field unassigned. But considering the script exists and is crucial (calls `IncrementChapter`), I think NI should display the generated filename instead. The safest way would be to fall back to this behaviour when the field is not set.

**Comment by Argent77** [comment]
Is that script actually used by the game even if it's not assigned to the ARE file?

**Comment by lynxlynxlynx** [comment]
Yes, I don't see anything else triggering the chapter text screen. It's the first thing that hits when entering the area.

**Comment by Argent77** [comment]
You could be right about that. I can't currently test IWD2, but I could reproduce the same effect in IWD. The game seems to use a script file of the same name as the ARE resource if the area script field in the ARE resource is empty.

**Comment by lynxlynxlynx** [comment]
Yes, I imagine it's the same as with the INI file, but definitely does not hold for WED.

**Comment by Argent77** [comment]
Added in dea2da3e10dce6ec3c0d705d06e219444a6fb082
