### ISSUE TITLE
Improved support for OS X

### ISSUE THREAD

**Issue by FredrikLindgren** [NearInfinityBrowser/NearInfinity#33]
OS X users would appreciate if NI behaved more like other OS X programs. Particularly mentioned was the keyboard shortcuts for copy/paste/cut, which are currently CTRL-c/v/x, but are otherwise Cmd-c/v/x on OS X.

Having devoted a grand 5 minutes to this, it seems these shortcuts are provided by the Java class itself, so it is less straightforward than it otherwise could be. Additionally, these new shortcuts should preferably be added as additions to the current shortcuts, so OS X users who have gotten used to using CTRL can continue to do so uninterrupted.

The issue was posted [here](http://www.shsforums.net/topic/45358-nearinfinity/?p=561308).

**Comment by Argent77** [comment]
Basic Mac OS X specific behavior mostly covered.
