### ISSUE TITLE
Additional overrides

### ISSUE THREAD

**Issue by FredrikLindgren** [NearInfinityBrowser/NearInfinity#35]
BGEE effectively has "movies" as N extra override folders, at least for movie files. However, NI only considers the one override, so any movie files located in "movies" are considered non-existent (as far as ResourceFactory.resourceExists() is concerned).

The straightforward solution would be to create a system where additional ID-dependent override-like folders can be defined and adjust ResourceFactory.loadResources() to give them all the override treatment.

**Comment by Argent77** [comment]
Most points already solved.
