### ISSUE TITLE
BAM mass export to PNG

### ISSUE THREAD

**Issue by Argent77** [NearInfinityBrowser/NearInfinity#74]
Feature request from [k7aesa7r](https://github.com/k7aesa7r):

Please could add the option in Mass Export window to BAM and ITM export as PNG?

Actually it just mass export MOS/PVRZ/TIS as PNG
http://1.ii.gl/vDIHgv8N.png

I would like extract all sprites from BAM and ITM, im not sure if the items sprites are in the folder ITM or they are with BAM , so if cant extract sprites from ITM dont need include it :)

Thankyou!

**Comment by Argent77** [comment]
[Added](https://github.com/Argent77/NearInfinity/commit/271c486a052e77b3e3a02c3a5923205b77a6291e).

**Comment by k7aesa7r** [comment]
Bro can you tell me how compile your source? Theres any guide or place where i can download it?

**Comment by Argent77** [comment]
You can download the latest snapshot release [here](https://github.com/Argent77/NearInfinity/releases). It already includes this feature.

If you still want to compile Near Infinity by yourself, you'll need to download and install the [Java SDK](http://www.oracle.com/technetwork/java/javase/downloads/index.html) as well as [Apache Ant](http://ant.apache.org/). After setting up tools and paths (consult the docs if needed), call ```ant``` on the command line in the NearInfinity source folder where you can find the file ```build.xml``` to start the building process. If everything went well you'll find ```NearInfinity.jar``` in the same folder.
