### ISSUE TITLE
Hovering walls in the area viewer

### ISSUE THREAD

**Issue by nerd-rage** [NearInfinityBrowser/NearInfinity#78]
After opening the first area of an IWD2 installation (AR1000.ARE) in the area viewer, I've noticed that wall polygons their Hovering flag (bit 2) have some weird shapes.

After some investigation, it seems that polygons marked as Hovering have their baseline (the first edge) unconnected. I guess, it's supposed to be the vertical projection of the wall on the ground.

Ignoring the first two edges when drawing seems to fix the problem, but I'm not sure how this should be reflected in the UI.

**Comment by Argent77** [comment]
Thanks for the information.

It is also consistent with wall polygons of other Infinity Engine games using this flag (e.g. AR1600 or AR1607 in BG2). Adding a fix should be trivial.

**Comment by Argent77** [comment]
Commit: https://github.com/Argent77/NearInfinity/commit/f64cad3d904cb2d0cdc2a6150370a4f420c65c39
