### ISSUE TITLE
BCS performance

### ISSUE THREAD

**Issue by FredrikLindgren** [NearInfinityBrowser/NearInfinity#83]
Is there anything that can be done to improve the performance of the BCS reader? Even with highlighting turned off, it takes me 40+ seconds to open a large BCS (ca 17k lines of BAF) with ca 500 HasItem() triggers.

**Comment by Argent77** [comment]
There appears to be a noticeable performance loss in more recent NI versions. I was able to track it down to the period between release 2.0-20160408 and 2.0-20160502. I'll see if I can improve performance somewhat.

**Comment by Argent77** [comment]
I have implemented a workaround by expanding `Options->Interactive script and resource names` (https://github.com/Argent77/NearInfinity/commit/8da656d5c0cfba7545a194583df7a3378d090540). Disable this option to see a noticeable speed increase when opening script files.

Main reason for the performance penalty (in general) is the usage of the new I/O API provided by `java.nio` in place of `java.io` which appears to produce a much higher latency compared to the previous API.

**Comment by FredrikLindgren** [comment]
The same script takes just under 20 seconds to open with Interactive turned off.
