### ISSUE TITLE
Regression in script compiler

### ISSUE THREAD

**Issue by FredrikLindgren** [NearInfinityBrowser/NearInfinity#85]
As of commit 5eccca13c1df05d977d2cf16c8b212a406570dce the script compiler, the feature autocheck BCS, and possibly other things, are broken on Linux and/or OpenJDK (1.8.0_141), because the functions CreMapCache.hasCreScriptName() and CreMapCache.hasAreScriptName() never return (resulting in the program becoming unresponsive). The same code seems to work without issues on Oracle's Windows runtime.

Steps to reproduce: enable Autocheck BCS and open 03POOL3.BCS in a ToB game. It seems the script name "Door1" is the problematic one, as 03POOL2.BCS can be opened with no problem.

**Comment by Argent77** [comment]
I can't reproduce this issue on my Linux VMs (Mint 18.2, OpenJDK 1.8.0_131). Scripts opened without issues or delays.

Tested on both Linux 32-bit and 64-bit VMs with BG2 and BG2EE. Also no change in behavior with NearInfinity.jar compiled on Windows or Linux.

Can you give more details about your system (OS, filesystem)?

**Comment by FredrikLindgren** [comment]
I'm using 64-bit Fedora 25 on Ext4.

The issue seems to be that if I just open NI and click on a script, nothing calls initialize(). If I add a call to initialize() to ensureInitialized(), the script opens after a few seconds delay. I can't find any references to either CreMapCache.init() or initialize() outside of CreMapCache.java. There are a few to reset(). (I'm not saying this is the right way to solve the problem, but it does narrow it down, I think.)

**Comment by Argent77** [comment]
I will set up a Fedora VM and see if I can reproduce this issue there.

`initialize()` is supposed to be called by `reset()` when the GUI is about to be initialized by NI's main routine. 

Maybe this stack trace can help narrow down the cause on your side:
```
org.infinity.util.CreMapCache.initialize(CreMapCache.java:146)
org.infinity.util.CreMapCache.init(CreMapCache.java:45)
org.infinity.util.CreMapCache.reset(CreMapCache.java:62)
org.infinity.NearInfinity$2.doInBackground(NearInfinity.java:312)
org.infinity.NearInfinity$2.doInBackground(NearInfinity.java:1)
javax.swing.SwingWorker$1.call(SwingWorker.java:295)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
javax.swing.SwingWorker.run(SwingWorker.java:334)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)
```

**Comment by FredrikLindgren** [comment]
Oh, for whatever reason, I have the checkScriptNames() option turned off, so reset() never calls init().

**Comment by Argent77** [comment]
With `autocheckBCS()` enabled and `checkScriptNames()` disabled I can reproduce the same issue on my Windows machine, so it's not limited to OpenJDK. I'll investigate it further.

**Comment by Argent77** [comment]
Fixed.

The issue was caused by an incomplete check of conditions which resulted in an endless loop when looking up CRE or ARE script names.

Commit: https://github.com/Argent77/NearInfinity/commit/cf25a0cababaf77fac82a87308131530ea2aa2be

**Comment by FredrikLindgren** [comment]
Since autochecking of BCS won't work without checking script names, perhaps it would be better to compact the two options into one. As it is now, the options leave it open for having a checked option that does not produce a result because another option is not checked.

**Comment by Argent77** [comment]
`Autcheck BCS` does more than just checking CRE and ARE script names. But I agree that it's reasonable to combine both options into one. They had been made separate options in the past for performance reasons. But that should no longer apply since the script compiler has been rewritten from scratch.

**Comment by FredrikLindgren** [comment]
Cool. Yeah, I seem to recall it being slower last time we talked about it.
