### ISSUE TITLE
NearInfinity prebuilt binaries

### ISSUE THREAD

**Issue by metamaker** [NearInfinityBrowser/NearInfinity#89]
I see source code for every release in https://github.com/NearInfinityBrowser/NearInfinity/releases. However, I don't see any prebuilt binaries. Since this is Java code, it is portable and should not require recompilation on every OS. Why not to include already built versions of NearInfinity in releases? It would save a lot of effort for lazy people like I am who don't develop in Java :)

**Comment by Argent77** [comment]
Hi metamaker!

Near Infinity is primarily developed on my own fork: https://github.com/Argent77/NearInfinity/

You can also find prebuilt binaries over there. The main project is only updated in irregular intervals.

Discussion is mainly done in the respective topics of [SHS](http://www.shsforums.net/topic/45358-nearinfinity/) and [Beamdog](https://forums.beamdog.com/discussion/30593/new-versions-of-nearinfinity-available/p1) forums. You can also find links to the prebuilt binaries there. Or visit the [Near Infinity Wiki](https://github.com/NearInfinityBrowser/NearInfinity/wiki) which answers many questions.

**Comment by metamaker** [comment]
@Argent77 Thanks for link! I somehow missed it.
