### ISSUE TITLE
Door flags

### ISSUE THREAD

**Issue by Displacer1** [NearInfinityBrowser/NearInfinity#90]
Door flags 12 - 31 are unused. Also bit 6 is commented out so I assume this is now unused, not sure about that though. This is directly from the .are header file for BG2 supplied by beamdog for modders Some may be used by PS:T however. Here is a copy of text from the header file for the flags:

/ bit flags
AREA_DOOROBJECTFLAGS_DOOROPEN                0x0001
AREA_DOOROBJECTFLAGS_DOORLOCKED              0x0002
AREA_DOOROBJECTFLAGS_TRAPRESET               0x0004
AREA_DOOROBJECTFLAGS_TRAPDETECTABLE          0x0008
AREA_DOOROBJECTFLAGS_BROKEN                  0x0010
AREA_DOOROBJECTFLAGS_CANTCLOSE               0x0020
//AREA_DOOROBJECTFLAGS_DETECTED                0x0040
AREA_DOOROBJECTFLAGS_SECRET                  0x0080
AREA_DOOROBJECTFLAGS_DETECTEDSECRET          0x0100
AREA_DOOROBJECTFLAGS_GATE                    0x0200     // means you can see though it
AREA_DOOROBJECTFLAGS_USEUPKEY                0x0400     // Subtract a use from the key every time that you toggle door
AREA_DOOROBJECTFLAGS_DONTCHECKCLOSED         0x0800     // don't check obstacles when closing door

**Comment by Argent77** [comment]
Thanks for the info. ARE door flags are already fully implemented in NI and appear to match the definitions listed by the header file. I can't say whether bit 6 is used, but it is set for the majority of doors, so I'll keep it for the time being.

**Comment by Displacer1** [comment]
Yea, but oddly enough its mostly just in PS:T. The other reason I posted was the flags after bit 12 are unused, at least for BGII, Again PS:T may use some of these. I'll go through PS:TEE areas and check if there are any flags used beyond bit 11, but as for BGII, they are unused, thought it might be useful to either remove the checkmarks for those flags from the interface, or at least mark them unused. I'll let you know what I find from Planescape, gonna take awhile to check all those doors...
