### ISSUE TITLE
Very slow (3 hours) loading of NI on Mac OS

### ISSUE THREAD

**Issue by FurloSK** [NearInfinityBrowser/NearInfinity#91]
All versions of NI after (not including) version **NearInfinity-2.0-20160408** hang during _"Loading override resources…"_ phase on my MacBook for very long time.

I have 41.000 items in Override folder, and while version 2.0-20160408 loads in ~20 seconds, latest version 2.1-20171027-rev2 took more than 3 hours to load, effectively making them unusable.

I have tested all versions after 2.0-20160408 and they all behave like the newest one, so the problem must be in one of [24 changes somewhere between those two versions](https://github.com/Argent77/NearInfinity/compare/v2.0-20160408...v2.0-20160501).

Mac-specific version downloadable from [AstroBryGuy's port](https://github.com/AstroBryGuy/NearInfinity-OSX) behaves the same way.

I have latest Java 8 Update 151 (but I tested it also with older Java 8 Update 105 released in 2016).
Running on macOS High Sierra 10.13.1.

**Comment by Argent77** [comment]
This is a big issue on all platforms. I have already invested many hours to find out and solve the cause of the long loading times without much success. I'll continue to look into it when I have more time.

The best way to reduce initial loading time for now is by biffing the override folder content, e.g. with the [Generalized Biffing](http://www.shsforums.net/files/file/741-generalized-biffing/) mod.

**Comment by Argent77** [comment]
Covered by #84
