### ISSUE TITLE
Edit Images .bam and .pvrz from Planescape Torment.

### ISSUE THREAD

**Issue by raulpuro** [NearInfinityBrowser/NearInfinity#92]
Hi,
    Well, this really is not a problem, it is a query, I would like to translate the images of the main menu of the game Planescape Torment, the images are in the files CGATTR.bam and STARTBUT.bam in the folders "Override" of their respective languages. Editing the * .bam files is no longer a problem thanks to Near Infinity, but they do not work in the game.   
    It seems that it is necessary to edit the images mos2000.pvrz .... mos2011.pvrz that are also in the "Override" folder, these files can also be opened with Near Infinity, but the images they show are very difficult to edit, it shows a bricolage of images. Is there another way to edit the images or generate a * .pvrz from a * .bam? if the * .bam files are deleted, the game does not give errors, but if the * .pvrz files are deleted the images are not displayed.

Greetings and thanks for your time and dedication.

**Comment by Argent77** [comment]
There is no need to touch the PVRZ files directly. They are handled by the BAM Converter automatically for BAM input files. BAM output files will create their own PVRZ files if you choose BAM output version "PVRZ-based (v2)". Just make sure to specify a PVRZ start index that isn't already occupied by the game to avoid overwriting or overriding existing files.

**Comment by raulpuro** [comment]
Hi
   Thanks for replying, I have also managed to edit the CGATTR.bam file, but I can not edit the STARTBUT.bam file, I assumed it could be a problem with the images png, but I have extracted all the images from the STARTBUT.bam file and created a bam file , with the unedited images putting the same cycles, changed the id, but the images do not show well in the game, I noticed that the original game contains 11 pvrz files for this file bam, mos2000.pvrz ... mos2010. pvrz, but near infinity to me only creates 8 files.
   Surely I'm doing something wrong, and I have it wrong configured but I do not know which is the correct configuration.

Greetings and happy holidays.

**Comment by Argent77** [comment]
The fewer number of pvrz files is just the result of a different packing algorithm used by NI, there is no need to worry. It would be more problematic if the resulting BAM referenced more PVRZ files than the original. In that case you would have to choose a range of pvrz indices that is not occupied by existing game resources (e.g. start at index 3000 or higher).

Judging from the last screenshot I'd say you forgot to copy all the required files (BAM and all associated PVRZ files) into the override folder.

**Comment by raulpuro** [comment]
Hi,

  Ffinally I had to delete and reinstall the game, but now everything works correctly.

Greetings and thanks.
