### ISSUE TITLE
Export Worldmap with active areas

### ISSUE THREAD

**Issue by khayman123** [NearInfinityBrowser/NearInfinity#93]
Hi. I've downloaded latest release of NI and I loved new view of .wmp files, which shows areas. Is it possible to add export as png function for this view ?

**Comment by Argent77** [comment]
I'll add it to my to-do list, but I can't promise anything.

**Comment by khayman123** [comment]
I'm very appreciate.

**Comment by Argent77** [comment]
Added to [v2.1-20180205](https://github.com/Argent77/NearInfinity/releases/tag/v2.1-20180205).
