### ISSUE TITLE
gfx storm on directdraw/direct3d/opengl

### ISSUE THREAD

**Issue by Insomniator** [NearInfinityBrowser/NearInfinity#96]
I have strange bug in Treeview, running with fraps i see over 4000 "page swapping/redraw window/some other gfx related" per second.
Win7 x64, GTX660 ver.353.06, in nvidia's control panel vsync=ON triplebuff=OFF, JRE 1.8.144

How to reproduce:
- open any *.dlg
- open Tree, select first line like "KELDOR.DLG (states:42, responses:68,...)" - no gfx storm
- select state with window "state trigger" - gfx storm
- select state without window "state trigger" - no storm
- select response with window "action" - gfx storm
- select response without window "action" - no storm

screens
![javaw_2018-09-30_01-50-28](https://user-images.githubusercontent.com/24399531/46250399-af77e500-c453-11e8-894a-c01e80b3368f.png)
![javaw_2018-09-30_01-55-27](https://user-images.githubusercontent.com/24399531/46250426-0ed5f500-c454-11e8-9679-a0656ab9594c.png)
![javaw_2018-09-30_01-58-46](https://user-images.githubusercontent.com/24399531/46250443-6c6a4180-c454-11e8-8f7d-e2b12bc80d1b.png)
![javaw_2018-09-30_01-51-46](https://user-images.githubusercontent.com/24399531/46250400-b0107b80-c453-11e8-97a0-f18eb6292325.png)

**Comment by Argent77** [comment]
I can reproduce this issue. I'll see what I can do.

**Comment by Argent77** [comment]
It seems to be an issue in an external module. Disabled the offending method for now with (hopefully) no visible change in behavior (88ac1df806c9f0a1fd4f9f3f96a3e9c2c9e94e91).
