### ISSUE TITLE
LICENSE.txt is missing in the project

### ISSUE THREAD

**Issue by Mingun** [NearInfinityBrowser/NearInfinity#97]
Files in the project contains following header:
```java
// Near Infinity - An Infinity Engine Browser and Editor
// Copyright (C) 2001 - 2005 Jon Olav Hauglid
// See LICENSE.txt for license information
```
but LICENSE.txt not exist

**Comment by Argent77** [comment]
There is a License.txt, but filename is not all uppercase.

[Fixed](https://github.com/Argent77/NearInfinity/commit/72000cf5b6e4bdbea9b80346fe9b285fb532ff83). Thanks.

**Comment by Mingun** [comment]
Ah... I think it will be better move it to the root of the repository

**Comment by Argent77** [comment]
The tool includes several different license files (for third-party libraries, etc.), which are all located at `org.infinity`. Moving them all to the root folder will only polute the folder structure needlessly.

**Comment by Mingun** [comment]
Why not store project license in the repository root and other licenses in the `org.infinity`? The project itself has one license and it is unimportant what licenses at dependences (of course, if the project license doesn't break them). As far as I know, it is the general practice.

Besides, it is good to specify the license in the github interface.

Anyway, I think that need highlight licenses location in the readme.

**Comment by Argent77** [comment]
I can't move license file to the repository root without losing access to it from the tool's Help menu. I could store a copy of the file however, to meet general practice.
