### ISSUE TITLE
Find unused strings consider PST bestiary, quest and GUI strings as unused

### ISSUE THREAD

**Issue by Mingun** [NearInfinityBrowser/NearInfinity#98]
And may be some other:
![bestiary](https://user-images.githubusercontent.com/450131/46257063-2e5d3400-c4cd-11e8-805d-bbfe8dcd5280.png)
![quests](https://user-images.githubusercontent.com/450131/46257065-2e5d3400-c4cd-11e8-8d4b-d590e9119f48.png)
![gui](https://user-images.githubusercontent.com/450131/46257064-2e5d3400-c4cd-11e8-9fc7-aa54cb378a4c.png)

**Comment by Argent77** [comment]
All fixed <sup>*</sup>

_<sup>*</sup> StringRefs in `UI.MENU` are not checked to reduce number of false positives._

**Comment by Mingun** [comment]
Could you explain, what false positives you mean? Maybe some examples. This would help in further investigating this problem

**Comment by Argent77** [comment]
The current algorithm for scanning strrefs in text files (which also includes .menu, .lua and .2da files) is quite inaccurate and counts everything that consists of one or more digits.

At least 95 percent of the numbers in `UI.MENU` describe data for positioning UI elements on screen or references to internal identifiers, indices or game statistics. Many strings in this file are also referenced indirectly through variables and lookup tables.

The majority of the content looks like this:
```
label
{
	area 192 191 236 235
	mosaic lua "characters[currentID].pstPortrait"
}
button
{
	area 974 12 50 50
	bam "XBUTT"
	action
	"
		e:GetActiveEngine():SelectEngine(worldScreen)
	"
}
```
The false positives rate could possibly be reduced by doing a more specific search for certain phrases that are known to contain strrefs, but that will still leave many instances which are either not detected (e.g. array content) or falsely detected as strrefs.

This is one example of array content with strrefs:
```
autoPauseToggles = { 
{'WEAPON_UNUSABLE_LABEL',37692, 5 , 0, 0},
{'END_OF_ROUND_LABEL',37694, 25, 0, 0},
{'ENEMY_SIGHTED_LABEL',68760, 26, 0, 0},
{'SPELL_CAST_LABEL',68761, 31, 0, 0},
{'TRAP_FOUND_LABEL',68762, 34, 0, 0}
}
```
But arrays could just as well contain anything else. You will know for certain only by considering the context (which is way outside the scope of NI).

This is not as problematic for LUA (and to a lesser extent 2DA) files where many numbers are actual strrefs. For 2DA files the detection rate could be improved by adding a blacklist filter for files that evidently don't contain strrefs.
