### ISSUE TITLE
PST dialog DALMIDIL has empty tree though it has one state and one response

### ISSUE THREAD

**Issue by Mingun** [NearInfinityBrowser/NearInfinity#99]
![dalmidil](https://user-images.githubusercontent.com/450131/47604576-1cf84080-da15-11e8-9a7b-50369f3930d8.png)

**Comment by Argent77** [comment]
It's working as intended. Dialog states without state trigger cannot be used to start conversations. This particular state is just used as a response for DYI'MINN.DLG. It is still possible to inspect the content of the DLG in the View or Edit tab.

**Comment by Mingun** [comment]
It is obvious that this dialog begins, and I think, it is used in cut scene. So I think that fix that I suppose in https://github.com/Argent77/NearInfinity/pull/14, correct.

The tree viewer shall show entries with which conversation can start, not necessary with what it will surely begin. As stated in https://gibberlings3.github.io/iesdp/file_formats/ie_formats/dlg_v1.htm, state 0 is always checked for a possibility of the beginning of conversation therefore it always shall be present at a tree

**Comment by Argent77** [comment]
That's right, dialog states are checked by the engine, starting at state 0. But as I stated before, only states with a condition evaluating to `true` will actually trigger a conversation.

In the example above, DALMIDIL.DLG state 0 is used as continuation of DYI'MINN.DLG state 44 in a cutscene that involves a couple of Githyanki. Adding the state as root element in the tree view would only confuse modders who are validating their own dialogs, leading them to believe their dialogs will actually trigger a conversation.

**Comment by Mingun** [comment]
Well, your argumentation looks convincing. However it a little than will help if there is a wish to look at a dialog in a tree, for example, in case of content investigation. Then I suggest to add setting **"Always show state 0 in the dialog tree"** to the menu and to draw such state in special color. If you are agree, I will update https://github.com/Argent77/NearInfinity/pull/14

**Comment by Argent77** [comment]
Yes, that would be acceptable.
